server:
  port: 10011     # 网关服务端口

myGateWayPasswd:
  asd4x8sdr8621dfvb4xcf65e

spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos服务地址
    gateway:
      routes: # 网关路由配置
        - id: user-service  # 路由标示，必须唯一
          uri: lb://userservice   # 路由的目标地址，也可以写 ip地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/user/** # 路径断言，判断路径是否以 /user开头，是则符合规则
        #          filters: # 局部过滤器
        #            - AddRequestHeader=ReferTo,${myGateWayPasswd}
        - id: orderservice
          uri: lb://orderservice
          predicates:
            - Path=/order/**

      #          filters:
      #            - AddRequestHeader=ReferTo,${myGateWayPasswd}
#      default-filters: # 全局过滤器
#        - AddRequestHeader=ReferTo,${myGateWayPasswd}
#      globalcors: # 全局的跨域处理
#        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: # 允许哪些网站的跨域请求
#              - "http://localhost:8090"
#            allowedMethods: # 允许的跨域ajax的请求方式
#              - "GET"
#              - "POST"
#              - "DELETE"
#              - "PUT"
#              - "OPTIONS"
#            allowedHeaders: "*" # 允许在请求中携带的头信息
#            allowCredentials: true # 是否允许携带cookie
#            maxAge: 360000 # 这次跨域检测的有效期





