server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud_db?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos服务地址
      discovery:
        cluster-name: BJ
#        namespace: 33bef7ee-b330-4b3c-b2b6-415316d1501e # 这里是dev环境--下次uuid可能会变，同一个namespace下的服务才能相互访问
#        ephemeral: false  # 是否是临时实例


#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka

feign:
  client:
    config:
      default: # default全局的配置
        loggerLevel: BASIC           # 日志级别，BASIC就是基本的请求和响应信息
  #      userservice                   # 只对 userservice有效
  #        loggerLevel: basic
  httpclient:
    enabled: true                   # 开启feign对HttpClient的支持
    max-connections: 200            # 最大的连接数
    max-connections-per-route: 50   # 每个路径的最大连接数

userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则----集群规则--优先同集群
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 负载均衡规则----随机


ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: userservice  # 指定饥饿加载的服务名称

mybatis:
  type-aliases-package: com.jchhh.user.pojo
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.jchhh: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS




